### ISSUE TITLE
not working if the computer is put to sleep mode

### ISSUE THREAD

**Issue by sjv-afk1** [leveson/bat#3]
If the laptop is put to suspend, then this feature doesn't work. Also, the persist function doesn't work. 

And for example if I use the following command : ./bat --threshold 60, I get asked for root password, but I always get authentication failure. So, I need to use SUDO with it.

This program only works temporarily( During the session). If subjected to suspend or restart, then it fails. 

I am using asus tuf a17 FA-706IH
operating system: ubuntu 20.04
kernel: 5.8.0-44-generic

**Comment by leveson** [comment]
Thank you for bringing up the issue. I will have a look into it.

Just to make sure that I understand, 
 
    1) when the laptop is put to suspend (or shut  down), the charging threshold is not set anymore upon restart, 
    2)  the persist argument does not work _at all_, 
    3)  when you run `bat --threshold 60` and get asked for the root password you get an authentication failure message but if you use `sudo bat --threshold 60` it works?

**Comment by sjv-afk1** [comment]
> Thank you for bringing up the issue. I will have a look into it.
> 
> Just to make sure that I understand,
> 
> 1. when the laptop is put to suspend (or shut  down), the charging threshold is not set anymore upon restart,
> 2. the persist argument does not work _at all_,
> 3. when you run `bat --threshold 60` and get asked for the root password you get an authentication failure message but if you use `sudo bat --threshold 60` it works?

1. YES ( I mean sleep mode when I say suspend) So, if I resume from sleep mode, then threshold is reset to 100.
2. YES
3. YES

**Comment by leveson** [comment]
Do you get any message after running `sudo bat --persist`?

**Comment by sjv-afk1** [comment]
> Do you get any message after running `sudo bat --persist`?

no

**Comment by leveson** [comment]
Sorry about that, just edited the comment to run a different command. Can you run this command `test -f /etc/systemd/system/bat.service && echo "TRUE"`?

**Comment by sjv-afk1** [comment]
> Sorry about that, just edited the comment to run a different command. Can you run this command `test -f /etc/systemd/system/bat.service && echo "TRUE"`?

 test -f /etc/systemd/system/bat.service && echo "TRUE"
TRUE

**Comment by leveson** [comment]
Please check if the file has any contents by running, `less /etc/systemd/system/bat.service`.

If it does, then run `systemctl enable bat.service` and tell me what happens. I have a feeling on Ubuntu you might have to run this with `sudo` but let me know what happens in the first instance (without `sudo`) and if everything works after running these.

**Comment by sjv-afk1** [comment]
> less /etc/systemd/system/bat.service



> Please check if the file has any contents by running, `less /etc/systemd/system/bat.service`.
> 
> If it does, then run `systemctl enable bat.service` and tell me what happens. I have a feeling on Ubuntu you might have to run this with `sudo` but let me know what happens in the first instance (without `sudo`) and if everything works after running these.

This is what I am getting after running first command:
[Unit]
Description=Set the battery charging threshold
After=multi-user.target
StartLimitBurst=0

[Service]
Type=oneshot
Restart=on-failure
ExecStart=/bin/bash -c 'echo 91 > /sys/class/power_supply/BAT?/charge_control_end_threshold'

[Install]
WantedBy=multi-user.target
        
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
(END)

and after running "systemctl enable bat.service" nothing happens. I tried using SUDO also.

**Comment by leveson** [comment]
Nothing happens as in there is no output after running the command or the battery threshold is still not persisting between restarts?

Can you run the following and send me the output? I might have to get Ubuntu installed to try to work this one out.

`sudo bat -t 60`

`sudo bat -p`

`systemctl status bat.service`

And just to make sure, you are running the latest version from the releases page right?

**Comment by sjv-afk1** [comment]
> systemctl status bat.service



> Nothing happens as in there is no output after running the command or the battery threshold is still not persisting between restarts?
> 
> Can you run the following and send me the output? I might have to get Ubuntu installed to try to work this one out.
> 
> `sudo bat -t 60`
> 
> `sudo bat -p`
> 
> `systemctl status bat.service`
> 
> And just to make sure, you are running the latest version from the releases page right?

Yes I am running the latest release. The following is the output:

sjv@dh1729:~/Binaries/bat1$ sudo ./bat -t 60
Identified face as sjv
Charging threshold set to 60.
sjv@dh1729:~/Binaries/bat1$ sudo ./bat -p
sjv@dh1729:~/Binaries/bat1$ systemctl status bat.service
● bat.service - Set the battery charging threshold
     Loaded: loaded (/etc/systemd/system/bat.service; enabled; vendor preset: e>
     Active: inactive (dead) since Mon 2021-03-08 15:25:59 IST; 2 days ago
   Main PID: 2554 (code=exited, status=0/SUCCESS)

Mar 08 15:25:59 dh1729 systemd[1]: Starting Set the battery charging threshold.>
Mar 08 15:25:59 dh1729 systemd[1]: bat.service: Succeeded.
Mar 08 15:25:59 dh1729 systemd[1]: Finished Set the battery charging threshold.
lines 1-8/8 (END)...skipping...
● bat.service - Set the battery charging threshold
     Loaded: loaded (/etc/systemd/system/bat.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2021-03-08 15:25:59 IST; 2 days ago
   Main PID: 2554 (code=exited, status=0/SUCCESS)

Mar 08 15:25:59 dh1729 systemd[1]: Starting Set the battery charging threshold...
Mar 08 15:25:59 dh1729 systemd[1]: bat.service: Succeeded.
Mar 08 15:25:59 dh1729 systemd[1]: Finished Set the battery charging threshold.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-8/8 (END)

**Comment by leveson** [comment]
Can you check if this fix works?

[bat.zip](https://github.com/leveson/bat/files/6122818/bat.zip)

**Comment by sjv-afk1** [comment]
> Can you check if this fix works?
> 
> [bat.zip](https://github.com/leveson/bat/files/6122818/bat.zip)

Not working. Do I need to restart the computer and test it again?

**Comment by leveson** [comment]
I think so. Judging by your output, everything should be working. The threshold level seems to be set to 91 and it should persist between restarts and sleep/suspend but not hibernation.

The only problem seems to have been with the call to set the threshold level which on Ubuntu didn't work because the root user appears to be locked by default but that should not be a problem with this version.

As a last resort, run `sudo bat --reset`, restart your computer, run `sudo bat -t 60`. If that does not work, show me the output to that along with the output to `cat /sys/class/power_supply/BAT?/charge_control_end_threshold`.

If that worked then, run `sudo bat -p` and show me the output to `cat /etc/systemd/system/bat.service` and `systemctl status bat.service`.

**Comment by sjv-afk1** [comment]
Okay, I will post it in few hours.

**Comment by sjv-afk1** [comment]
> cat /sys/class/power_supply/BAT?/charge_control_end_threshold

sjv@dh1729:~/Binaries/bat2$ sudo ./bat -t 60
Identified face as sjv
Charging threshold set to 60.
sjv@dh1729:~/Binaries/bat2$ sudo ./bat --persist
sjv@dh1729:~/Binaries/bat2$ cat /sys/class/power_supply/BAT?/charge_control_end_threshold
60

**Comment by leveson** [comment]
Okay. That narrows it down. Without doing anything else, when you shut it down and boot again, is it still set to 60?

**Comment by sjv-afk1** [comment]
> Okay. That narrows it down. Without doing anything else, when you shut it down and boot again, is it still set to 60?

Yes, it shows that it is set to 60.

**Comment by leveson** [comment]
Let me know if [this](https://github.com/leveson/bat/files/6170955/bat.zip) fixes the problem with the threshold not persisting after sleep/suspend. But first run `sudo rm /etc/systemd/system/bat.service`.

**Comment by sjv-afk1** [comment]
> Let me know if [this](https://github.com/leveson/bat/files/6170955/bat.zip) fixes the problem with the threshold not persisting after sleep/suspend. But first run `sudo rm /etc/systemd/system/bat.service`.

Didn't work.

**Comment by leveson** [comment]
Let's try this [one](https://github.com/leveson/bat/files/6195782/bat.zip).

**Comment by leveson** [comment]
Seems to be an issue with systemd. Can you check which version is installed on your system by running `systemctl --version`?

**Comment by sjv-afk1** [comment]
systemctl --version
systemd 245 (245.4-4ubuntu3.4)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Comment by leveson** [comment]
Curious. I’ll have to get a distribution of Ubuntu to understand exactly what is going on but it could take a while.

**Comment by agilum** [comment]
Hi, 

I am using ubuntu20.4+kernel 5.10+systemd 245 (245.4-4ubuntu3.6).

In may case bat-h, bat-c, bat-s works as it should
bat -t or sudo bat -t exit status 1
bat -p or sudo bat -p exit status 1 and service not starting
bat - r ok after sudo password

Can You help?

**Comment by leveson** [comment]
Difficult to say right now. But I will look into this and post here as soon as I manage to get a distribution of Ubuntu.

**Comment by PrathamBhatTech** [comment]
I have the same problem. Looking at your previous suggestions i have run the following:

>`test -f /etc/systemd/system/bat.service && echo "TRUE"`
   Returns nothing
>  `less /etc/systemd/system/bat.service`
    Returns "no such file or directory"
>  `systemctl --version`
    Returns the verision of systemd as 247

**Comment by leveson** [comment]
Cheers. I have had exams so I haven't had the time to work on a fix yet but I should be able to download Ubuntu and get to working on it in the comings weeks.

**Comment by leveson** [comment]
Here is a proposed fix.

[bat.zip](https://github.com/leveson/bat/files/6631269/bat.zip)

Let me know if it works.

For everyone else, if you could show me the output of the following command,

```shell
test -f /sys/class/power_supply/BAT?/charge_control_end_threshold && echo "TRUE"
```

Ubuntu 20.04 does not seem to expose the charging threshold variable. At least when running it in a VM. But you get an output value of ```TRUE``` to the above command then I can look further into it.

**Comment by PrathamBhatTech** [comment]
It works great. 
Thank you for all the help.

**Comment by leveson** [comment]
Thank you for feedback! Can you post the output of the following command so that I can finalise a release?

```shell
systemctl status bat-sleep.service
```

**Comment by PrathamBhatTech** [comment]
'systemctl status bat-sleep.service'

Output(When the charging is stopped at 60%):

● bat-sleep.service - Persist the battery charging threshold after hibernation
     Loaded: loaded (/etc/systemd/system/bat-sleep.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

**Comment by leveson** [comment]
Thank you.

**Comment by igor-frolikov** [comment]
Works fine after restart, but fails after return from sleep mode (while still shows correct threshold)

OS: Manjaro Linux [x86_64]
Host: VivoBook_ASUSLaptop X513IA_M513IA 1.0
Kernel: 5.10.52-1-MANJARO
Packages: 1277 (pacman)[stable]
Shell: bash 5.1.8
DE: KDE Plasma 5.22.3
WM: KWin (X11)
CPU: AMD Ryzen 5 4500U with Radeon Graphics (6) @ 2.375GHz
GPU: AMD ATI Renoir
Memory: 1720MiB / 15484MiB (11%)
Disk (/): 12GB / 100GB (12%)
Battery: 90% [Not charging]
