### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by fabricio8800** [leveson/bat#4]
When I execute the command below it returns "Authentication failure.":

./bat --threshold 60

The problem happens using root or sudo.

**Comment by leveson** [comment]
Which distribution are you running?

**Comment by fabricio8800** [comment]
Fedora 33.

Em qui, 11 de mar de 2021 02:48, Tshaka Eric Lekholoane <
***@***.***> escreveu:

**Comment by leveson** [comment]
I am working on a fix to a related problem that appears on Ubuntu. When that is done, I will post the binary and then you can let me know if it fixes your problem as well? If not then perhaps we can explore it further.

**Comment by leveson** [comment]
Can you let me know if this fix works before I put it to release?

[bat.zip](https://github.com/leveson/bat/files/6122818/bat.zip)

**Comment by fabricio8800** [comment]
New error:

[root@fedora Downloads]# ./bat --threshold 80
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.setThreshold(0x50)
	/home/lvsnxo/dev/bat/bat.go:165 +0x40c
main.main()
	/home/lvsnxo/dev/bat/bat.go:219 +0x3fc

**Comment by leveson** [comment]
What's the manufacturer/model of your laptop?

**Comment by fabricio8800** [comment]
Is a Dell Inspiron 5368.

**Comment by leveson** [comment]
I am afraid I don't think this will work with your laptop. 

The variables that control the charging threshold are vendor specific, they even vary within different models from the same manufacturer and so far this has only been tested on ASUS machines.

I will research the problem, but your best bet might be [this command-line application from Dell](https://www.dell.com/support/kbdoc/en-uk/000178000/dell-command-configure) that can do this sort of thing and some scripts from [this repository](https://github.com/glynhudson/dell-charge-limit) that abstract parts of the application to set the charging threshold.

**Comment by fabricio8800** [comment]
Ok, thanks.

**Comment by leveson** [comment]
Cheers ;)

**Comment by fabricio8800** [comment]
I solve my problem with:

smbios-battery-ctl --set-custom-charge-interval "low high" and smbios-battery-ctl --set-charging-mode custom

**Comment by leveson** [comment]
That's interesting. Did you have to install anything or did that come with your system?

**Comment by fabricio8800** [comment]
I installed the smbios-utils package.

**Comment by leveson** [comment]
Thank you for letting me know. I think I will update the readme to redirect anyone with a Dell laptop to that package.
