### ISSUE TITLE
'This program is most likely not compatible with your system' on ASUS with Linux kernel 5.4.0-70

### ISSUE THREAD

**Issue by OmeCor** [leveson/bat#6]
First, thanks for writing this and giving it to the community. I appreciate it. I just bought a new battery for my N750JV, but already it lasts only 60 minutes max... :-/ So, I was happy to come across your utility. However, when I enter

`sudo ./bat --threshold 80`

the utility tells me "This program is most likely not compatible with your system."

I have an ASUS N750JV with the latest BIOS upgrade and Linux kernel 5.4.0-70-generic. Could you explain what could be wrong?

Best regards, OmeCor

**Comment by leveson** [comment]
Hi (:

It generally means the program cannot find the underlying variable that controls the charging threshold. How this is exposed varies depending on the manufacturer and in some cases between different models of the same manufacturer.

You can try running the following command and see if its possible to make it work with your system.

```
sudo find /sys/ -name "charge_control*"
```
